name: pull-request

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    uses: ./.github/workflows/php-verify.yml
    permissions:
      contents: read
